dependencies:
  module:
    - text
content:
  field_teaser_image:
    type: entity_reference_entity_view
    weight: 2
    region: content
    label: hidden
    settings:
      view_mode: default
      link: false
    third_party_settings: {  }
  field_teaser_text:
    type: text_default
    weight: 3
    region: content
    label: hidden
    settings: {  }
    third_party_settings: {  }