dependencies:
  module:
    - image
content:
  field_video_upload_preview:
    type: media_thumbnail
    weight: 2
    region: content
    label: hidden
    settings:
      image_style: thumbnail
      image_link: content
    third_party_settings: {  }