content:
  field_copyright:
    type: entity_reference_autocomplete
    weight: 12
    region: content
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }