content:
  field_copyright:
    type: entity_reference_label
    weight: 10
    region: content
    label: above
    settings:
      link: false
    third_party_settings: {  }
  field_description:
    type: text_default
    weight: 11
    region: content
    label: above
    settings: {  }
    third_party_settings: {  }