dependencies:
  config:
    - field.field.media.video.field_media_accessibility
content:
  field_media_accessibility:
    weight: 7
    label: above
    settings:
      link: true
    third_party_settings: {  }
    type: entity_reference_label
    region: content
