dependencies:
  config:
    - field.field.media.video.field_media_duration
    - field.field.media.video.field_media_transcription
content:
  field_media_duration:
    weight: 9
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    type: duration
    region: content
  field_media_transcription:
    weight: 10
    label: above
    settings: {  }
    third_party_settings: {  }
    type: text_default
    region: content