dependencies:
  config:
    - field.field.media.video_upload.field_copyright
    - field.field.media.video_upload.field_description
content:
  field_copyright:
    type: entity_reference_label
    weight: 7
    region: content
    label: above
    settings:
      link: false
    third_party_settings: {  }
  field_description:
    type: text_default
    weight: 8
    region: content
    label: above
    settings: {  }
    third_party_settings: {  }